### ISSUE TITLE
Unicode isus when using ukraine language

### ISSUE THREAD

**Issue by shramkoaleksey90** [javadev/moneytostr-russian#17]
Hello!
Thanks for your library. It was very helpful for me in my project. A great job is done!!

However, after using I noticed the following things:
The library uses character '\u2019' as a single quote for all numbers except 19 where it uses '\u0027', and uses 'LATIN SMALL LETTER I' (\u0069) instead of 'CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I' (\u0456) in such words: 'шiстнадцять', 'сiмнадцять', 'вiсiмнадцять'.

Could you unify the symbols, please?

**Comment by javadev** [comment]
Hi @shramkoaleksey90 

Thank you for the issue.

I prepared a fix.
