### ISSUE TITLE
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

### ISSUE THREAD

**Issue by ciukstar** [javadev/moneytostr-russian#8]
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

**Comment by javadev** [comment]
Hi, you may try to add this dependency to your maven project:

```xml
<dependency>
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis</artifactId>
    <version>1.4.01</version>
</dependency>
```

**Comment by ciukstar** [comment]
Thanks! With version 1.4.01 it worked. Earlier, I tried with 2.0.2 without success.

**Comment by javadev** [comment]
I moved data definition to the class file. There is no xml.parser needed.

**Comment by ciukstar** [comment]
Thanks for notification

**Comment by javadev** [comment]
The XML configuration has been substituted with a JSON string.
