### ISSUE TITLE
Negative number

### ISSUE THREAD

**Issue by NullaWhale** [javadev/moneytostr-russian#9]
program doesn't work correctly if the number is negative.

**Comment by javadev** [comment]
Hi, @NullaWhale !

What is expected value for the negative numbers?

**Comment by NullaWhale** [comment]
For example, word "minus" in the beginning of the result string

**Comment by javadev** [comment]
I created a PR with minus support for java https://github.com/javadev/moneytostr-russian/pull/10

**Comment by NullaWhale** [comment]
Did it for JS with PR too

**Comment by javadev** [comment]
I added support for javascript, https://github.com/javadev/moneytostr-russian/pull/12
